# The URL the site will be built for
title = "Seoul Rust"
base_url = "https://seoul.rs/"
#description = "Seoul Rust, seoul.rs"

theme = "zola-bearblog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
build_search_index = true

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
  { name = "authors", feed = true },
]

default_language = "en"

generate_feeds = true

author = "seoul.rs user"

[translations]
no_posts = "No Post yet"
remove_filter = "Remove Filter"
filtering_for = "Filter for"
made_with = "Made With"
table_of_contents = "Table of Contents"
language = "Language"
site = "Site"

[languages.ko]
title = "서울 러스트"
#description = "Ein Zola-theme basiert auf Bear Blog."

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
  { name = "authors", feed = true },
]


[languages.ko.translations]
no_posts = "등록된 게시물이 없습니다."
remove_filter = "Remove Filter"
filtering_for = "Filter for"
made_with = "Made With"
table_of_contents = "목차"
language = "Language"
site = "Site"

[markdown]
render_emoji = true

[extra]
date_format = "%Y-%m-%d"
webserver_sends_csp_headers = true
language_switcher = true
hide_made_with_line = true
translations = [
  { code = "en", name = "English" },
  { code = "ko", name = "한국어" },
]


[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = false

[[extra.main_menu]]
name = "Home"
name_ko = "홈"
url = "@/_index.md"

[[extra.main_menu]]
name = "News"
name_ko = "소식"
url = "@/news/_index.md"

[[extra.main_menu]]
name = "Blog"
name_ko = "블러그"
url = "@/blog/_index.md"
